[package]
name = "time-ledger"
version = "0.2.2"
edition = "2021"

[lib]
name = "time_ledger_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
ledger-core = { path = "../crates/ledger-core" }
tauri-plugin-nearby = { path = "../plugins/tauri-plugin-nearby" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
iana-time-zone = "0.1"

[target.'cfg(not(target_os = "android"))'.dependencies]
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "~2.11"
